name: netlify-files
description: >-
  Nuxt module to create new _headers, _redirects and netlify.toml files for
  Netlify or to use existing ones
long_description: >-
  Nuxt module to create new _headers, _redirects and netlify.toml files for
  Netlify or to use existing ones
repo: nuxt-community/netlify-files-module
npm: '@nuxtjs/netlify-files'
type: module
icon: netlify.png
github: 'https://github.com/nuxt-community/netlify-files-module'
website: 'https://github.com/nuxt-community/netlify-files-module'
learn_more: 'https://www.netlify.com/'
keywords:
  - community
categories:
  - deployment
maintainers:
  - name: Alexander Lichter
    github: manniL
    twitter: TheAlexLichter
    avatar: 'https://github.com/manniL.png'
