name: applicationinsights
description: AppInsights module for Nuxt.js
long_description: ''
repo: nuxt-community/applicationinsights-module
npm: '@nuxtjs/applicationinsights'
type: module
icon: application-insights.png
github: 'https://github.com/nuxt-community/applicationinsights-module'
website: 'https://github.com/nuxt-community/applicationinsights-module'
learn_more: ''
keywords: []
categories:
  - analytics
labels:
  - community
maintainers:
  - name: Dmitry Molotkov
    github: aldarund
    avatar: 'https://github.com/aldarund.png'
