name: applicationinsights
description: AppInsights module for Nuxt.js
long_description: >-
  AppInsights module for Nuxt.js. The module enables event logging through
  Application Insights. Application Insights, a feature of Azure Monitor, is an
  extensible Application Performance Management (APM) service for developers and
  DevOps professionals.
repo: nuxt-community/applicationinsights-module
npm: '@nuxtjs/applicationinsights'
type: module
icon: application-insights.png
github: 'https://github.com/nuxt-community/applicationinsights-module'
website: 'https://github.com/nuxt-community/applicationinsights-module'
learn_more: 'https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview'
keywords: []
categories:
  - monitoring
labels:
  - community
maintainers:
  - name: Dmitry Molotkov
    github: aldarund
    avatar: 'https://github.com/aldarund.png'
